# Generated by Django 4.2.4 on 2023-08-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='added',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='energy',
            name='published',
            field=models.TextField(max_length=100),
        ),
    ]
